name: Actionlint with reviewdog

on:
  push:
    branches:
      - main
      - master
  pull_request:
  merge_group:

jobs:
  actionlint:
    name: Actionlint with reviewdog
    uses: book000/templates/.github/workflows/reusable-actionlint.yml@052041d0119ac65c18cbb1347cf9de0fa41e46ec # master
