name: Actionlint with reviewdog

on:
  push:
    branches:
      - main
      - master
  pull_request:
  merge_group:

jobs:
  actionlint:
    name: Actionlint with reviewdog
    uses: book000/templates/.github/workflows/reusable-actionlint.yml@1f725b61fe3b897dde4fc3c02d8f9496d3cdb428 # master
