name: hadolint

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - "dockerfiles/**"

jobs:
  list-files:
    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.list-files.outputs.files }}

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 📄 List Dockefile files
        id: list-files
        run: |
          # git diff --name-only の結果をもとに、Dockerfile 拡張子のファイルを取得して、JSON配列として $GITHUB_OUTPUT に files として出力する
          echo "files=[$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E 'Dockerfile$' | sed -r -e 's/dockerfiles\/(.+).Dockerfile/\1/' -e 's/^/"/' -e 's/$/",/' | tr -d '\n' | sed -e 's/,$//')]" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: list-files

    strategy:
      matrix:
        file: ${{ fromJson(needs.list-files.outputs.files) }}
      fail-fast: false

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 🐳 hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: dockerfiles/${{ matrix.file }}.Dockerfile
