name: Generate README.md

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

# workflows/*.yml 以下のファイルを取得し、### add-reviewer.yml\n\n```\nmkdir -p .github/workflows ; wget -O .github/workflows/add-reviewer.yml https://raw.githubusercontent.com/book000/templates/master/workflows/add-reviewer.yml\n``` のようにする
# .github/templates.md を取得し、 <!-- templates --> に挿入する
# README.md に書き込む
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install dependencies
        run: |
          yarn add js-yaml

      - name: Generate readme
        run: |
          node scripts/generate-readme.js

      - name: Commit and push
        if: github.event_name == 'push'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md && \
          git commit -m "feat: Update README.md" && \
          git push || \
            true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: README.md
          path: README.md
