name: Auto add reviewer

on:
  workflow_call:
    inputs:
      actors:
        description: Target actors (comma separated)
        type: string
        default: dependabot[bot],renovate[bot],github-actions[bot],book000
      reviewers:
        description: Reviewers (comma separated)
        type: string
        default: book000

permissions:
  contents: read
  pull-requests: write

jobs:
  add-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        run: |
          # Use printf to safely handle the input without shell injection
          ACTORS=$(printf '%s' "${{ inputs.actors }}" | jq -R -c 'split(",") | map(select(length > 0) | ltrimstr(" ") | rtrimstr(" "))')
          echo "actors: $ACTORS"
          echo "is-need-add-reviewer=$(printf '%s' "$ACTORS" | jq -r --arg actor "${{ github.actor }}" '. | contains([$actor]) | not')" >> ""$GITHUB_OUTPUT""

      - name: Add reviewer
        uses: actions/github-script@v8
        if: ${{ steps.setup.outputs.is-need-add-reviewer == 'true' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.requestReviewers({
              ...context.repo,
              pull_number: context.issue.number,
              reviewers: "${{ inputs.reviewers }}".split(",")
            })
