name: Auto add reviewer

on:
  workflow_call:
    inputs:
      actors:
        description: Target actors (comma separated)
        type: string
        default: dependabot[bot],renovate[bot],github-actions[bot],book000
      reviewers:
        description: Reviewers (comma separated)
        type: string
        default: book000

jobs:
  add-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        run: |
          ACTORS=$(echo "${{ inputs.actors }}" | jq -R -c 'split(",") | map(select(length > 0) | ltrimstr(" ") | rtrimstr(" "))')
          echo "actors: $ACTORS"
          echo "is-need-add-reviewer=$(echo $ACTORS | jq -r '. | contains(["${{ github.actor }}"]) | not')" >> $GITHUB_OUTPUT

      - name: Add reviewer
        uses: actions/github-script@v7
        if: ${{ steps.setup.outputs.is-need-add-reviewer == 'true' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.requestReviewers({
              ...context.repo,
              pull_number: context.issue.number,
              reviewers: "${{ inputs.reviewers }}".split(",")
            })
